version: '3.8'

services:
  hugo:
    build:
      context: ./hugo
      dockerfile: Dockerfile
    ports:
      - "1313:1313"

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

